version: '3.8'

services:

#  postgres:
#    image: postgres:15
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: flightdb
#      POSTGRES_USER: flightuser
#      POSTGRES_PASSWORD: flightpass
#    volumes:
#      - ./src/main/resources/data-postgres.sql:/docker-entrypoint-initdb.d/data-postgres.sql  # Init script
#    networks:
#      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: flights-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/main/resources/flightdata_postgres.sql:/docker-entrypoint-initdb.d/flightdata_postgres.sql  # Init script
    ports:
      - "5432:5432"
    networks:
      - app-network


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flight-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/flightdb
#      - SPRING_DATASOURCE_USERNAME=flightuser
#      - SPRING_DATASOURCE_PASSWORD=flightpass
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
